INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("be", "bad", "bedt", "ask" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("bedra", "bedrog", "bedratt", "cheat" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("binde", "bandt", "bundet", "bind" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("bite", "bet", "bitt", "bite" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("brekke", "brakk", "brukket", "break" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("brenne", "brant", "brent", "burn" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("bringe", "brakte", "brakt", "bring" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("bryte", "brøt", "brutt", "violate, break" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("burde", "burde", "burdet", "ought to" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("by", "bød", "budt", "offer" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("bære", "bar", "båret", "bear, endure" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("dra", "dro/drog", "dratt/dradd", "drag, go" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("drikke", "drakk", "drukket", "drink" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("drive", "drev", "drevet", "drive, operate" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("dø", "døde", "dødd", "die" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("falle", "falt", "falt", "fall" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("finne", "fant", "funnet", "find" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("fly", "fløy", "fløyet/flydd", "fly" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("forlate", "forlot", "forlatt", "forgive" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("forsvinne", "forsvant", "forsvunnet", "disappear" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("fortelle", "fortalte", "fortalt", "tell" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("fryse", "frøs", "forsset", "freeze" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("følge", "fulgte", "fulgt", "follow" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("få", "fikk", "fått", "get" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("gi", "ga/gav", "gitt", "give" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("gjøre", "gjorde", "gjort", "do" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("gripe", "grep", "grepet", "grip" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("gråte", "gråt", "grått", "cry" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("gå", "gikk", "gått", "go, walk" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("ha", "hadde", "hatt", "have" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("henge", "hang", "hengt", "hang" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("hete", "het", "hett", "name" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("hjelpe", "hjalp", "hjulpet", "help" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("holde", "holdt", "holdt", "hold" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("innby", "innbød", "innbudt", "invite" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("komme", "kom", "kommet", "come" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("kunne", "kunne", "kunnet", "can" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("la", "lot", "latt", "let, allow" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("le", "lo", "ledd", "laugh" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("legge", "la", "lagd", "lay" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("ligge", "lå", "ligget", "lie" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("lyve", "løy", "løyet", "tell a lie" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("løpe", "løp", "løpt", "run" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("måtte", "måtte", "måttet", "have to" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("oversette", "oversatte", "oversatt", "translate" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("se", "så", "sett", "see" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("selge", "solgte", "solgt", "sell" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("sette", "satte", "satt", "set" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("si", "sa", "sagt", "say" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("sitte", "satt", "sittet", "sit" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("skrive", "skrev", "skrevet", "write" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("skulle", "skulle", "skullet", "shall" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("skyte", "skjøt", "skutt", "shoot" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("slippe", "slapp", "sloppet", "drop" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("slå", "slo", "slått", "hit" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("sove", "sov", "sovet", "sleep" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("spørre", "spurte", "spurt", "ask" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("stjele", "stjal", "stjålet", "steal" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("stå", "sto, stod", "stått", "stand" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("synge", "sang", "sunget", "sing" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("ta", "tok", "tatt", "take" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("telle", "talte", "talt", "count" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("treffe", "traff", "truffet", "meet" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("tvinge", "tvang", "tvunget", "force" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("velge", "valgte", "valgt", "choose" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("ville", "ville", "villet", "want" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("vinne", "vant", "vunnet", "win" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("vite", "visste", "visst", "know" );
INSERT INTO table_norsk ( infinitive, preateritum, participle, meaning ) VALUES ("være", "var", "vært", "be" );
